# Generated by Django 5.1.5 on 2025-02-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('Study_Hours_Per_Day', models.FloatField()),
                ('Extracurricular_Hours_Per_Day', models.FloatField()),
                ('Sleep_Hours_Per_Day', models.FloatField()),
                ('Social_Hours_Per_Day', models.FloatField()),
                ('Physical_Activity_Hours_Per_Day', models.FloatField()),
                ('Stress_Level', models.FloatField()),
                ('GPA', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
