# Generated by Django 5.1.5 on 2025-02-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentperformance',
            name='AttendanceRate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='ExtraCurricularActivities',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='Gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='Major',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='PartTimeJob',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentperformance',
            name='StudyHoursPerWeek',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='Stress_Level',
            field=models.IntegerField(),
        ),
    ]
